replicaCount: 1

environment:
  name: local

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: hello.localhost
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

secretEnv:
  enabled: true
  secretName: hello-app-secret
