environment:
  name: staging

replicaCount: 1

image:
  repository: localhost:5001/terraform-practice/hello-app
  tag: "act-20260616115731"
  pullPolicy: IfNotPresent

ingress:
  hosts:
    - host: hello-staging.localhost
      paths:
        - path: /
          pathType: Prefix
