apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-dev
  namespace: hello-app
spec:
  provider:
    vault:
      server: http://host.docker.internal:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hello-app-secret
  namespace: hello-app
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-dev
    kind: SecretStore
  target:
    name: hello-app-secret
    creationPolicy: Owner
  data:
    - secretKey: message
      remoteRef:
        key: hello-app
        property: message
    - secretKey: api_key
      remoteRef:
        key: hello-app
        property: api_key
