apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  labels:
    app.kubernetes.io/name: hello-app-secrets
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/environment: {{ .Values.environment.name | quote }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.targetName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: message
      remoteRef:
        key: {{ .Values.vault.remoteKey | quote }}
        property: message
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: api_key
      remoteRef:
        key: {{ .Values.vault.remoteKey | quote }}
        property: api_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
