apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
    app.kubernetes.io/name: hello-app-secrets
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/environment: {{ .Values.environment.name | quote }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.mountPath | quote }}
      version: v2
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.tokenSecretName }}
          key: {{ .Values.vault.tokenSecretKey }}
