apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: local-platform
  source:
    repoURL: https://github.com/Sungyoun-Kim/terraform-practice
    targetRevision: main
    path: gitops/hello-app-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
