apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: local-platform
  source:
    repoURL: https://github.com/Sungyoun-Kim/terraform-practice
    targetRevision: main
    path: charts/hello-app
    helm:
      releaseName: hello-app
      valueFiles:
        - values.yaml
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
